# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      id: npm-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - run: npm ci
      if: steps.npm-cache.outputs.cache-hit != 'true'
    - run: npm run eslint -- -o checkstyle-fe.xml -f junit
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: checkstyle-artifact
        path: checkstyle-fe.xml
    - name: Publish coding style report
      uses: mikepenz/action-junit-report@v1
      if: ${{ always() }}
      with:
        check_name: 'Coding style Report'
        report_paths: 'checkstyle-fe.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: npm t -- --ci --reporters=jest-junit --runInBand
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: unit-test-artifact
        path: junit.xml
    - name: Publish unit test report
      uses: mikepenz/action-junit-report@v1
      if: ${{ always() }}
      with:
        check_name: 'Unit test Report'
        report_paths: 'junit.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}