name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #- name: Validate composer.json and composer.lock
    #  run: composer validate

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Check php coding style
      run: |
        FILES=$(git diff --name-only HEAD master);
        if [ ! -z "$FILES" ]; then phpcs $FILES; fi
    #  run: composer run codestyle:ci
    #- run: ./vendor/bin/cs2pr ./build/checkstyle-be.xml
    #  if: always()

    #- run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

    #- name: Run linters
    #  uses: wearerequired/lint-action@v1
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    # Enable linters
    #    php_codesniffer: true
    #    # Optional: Ignore warnings
    #    php_codesniffer_args: "--standard=./ruleset.xml ./src"

    #- name: Lint Code Base
    #  uses: github/super-linter@v3
    #  env:
    #    VALIDATE_ALL_CODEBASE: false
    #    VALIDATE_PHP_PHPCS: true
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Run test suite
    #  run: ./vendor/bin/phing unittest

    - name: Checkout Private GitHub Action Repo
      uses: actions/checkout@v2
      if: always()
      with:
        repository: kduret/custom-github-action
        path: my-action
        ref: master
        token: ${{ secrets.custom_github_action }} # stored in GitHub secrets
    - name: Run My Action
      uses: ./my-action
      if: always()
      with:
        who-to-greet: 'Kev'

    - name: Annotate pr
      if: always()
      run: |
        cat checkstyle-be.xml
        ./my-action/cs2pr.php checkstyle-be.xml
