name: PR formatter

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: 'fix\(ci\)' # Regex the title should match.
        github_token: ${{ github.token }} # Default: ${{ github.token }}